on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SuperFola/is-build-action@master
        with:
          path-to-script: 'example.iss'